language: c
env:
  global:
  - CODECOV_TOKEN: a3f20f77-117b-47f4-ba11-19de49099a25
compiler:
- clang
- gcc
before_script:
- autoreconf -i
script:
- ./configure && make
after_success:
- bash <(curl -s https://codecov.io/bash)
